# Generated by Django 4.1.5 on 2023-02-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('software', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareEngineer',
            fields=[
                ('engineer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('engineer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareTraining',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('software', models.CharField(max_length=100)),
                ('engineer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.softwareengineer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEngineerLookup',
            fields=[
                ('lookup_id', models.AutoField(primary_key=True, serialize=False)),
                ('engineer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.softwareengineer')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
    ]
